development:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123456789"

production:
  secret_token: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  secret_key_base: <%= ENV['STRIPE_SECRET_KEY'] %>
